services:
  website:
    build: ./website
    environment:
      - MODSEC_RULE_ENGINE=on
    ports:
      - "80:80"
    secrets:
      - ssl_key
      - ssl_crt
    volumes:
      - ./website/react:/app
    container_name: website
    restart: unless-stopped
  
secrets:
  ssl_key:
    file: ../secrets/ssl.key
  ssl_crt:
    file: ../secrets/ssl.crt
